### PR TITLE
[minSdkVersion] set to 14

### PR DESCRIPTION
**Pull request by Humilton**
Signed-off-by: Hamilton <d63hbz@gmail.com>

minSdkVersion set to lower can support more advices.

### CODE REVIEW

**Comment by 4ntoine** [comment]
Min SDK version 21 is required in `webview` module because of  https://github.com/adblockplus/libadblockplus-android/blob/master/libadblockplus-android-webview/src/org/adblockplus/libadblockplus/android/webview/AdblockWebView.java#L927

Android WebViewClient with `WebResourceRequest` argument is available starting Android 21:
https://developer.android.com/reference/android/webkit/WebViewClient.html#shouldInterceptRequest(android.webkit.WebView, android.webkit.WebResourceRequest)

**Comment by 4ntoine** [comment]
Also here is why 16 is required in main module:
https://github.com/adblockplus/libadblockplus-android/blob/master/libadblockplus-android/src/org/adblockplus/libadblockplus/android/ConnectionType.java#L42

https://developer.android.com/reference/android/net/ConnectivityManager.html#isActiveNetworkMetered()

**Comment by Humilton** [comment]
@TargetApi(Build.VERSION_CODES.LOLLIPOP) can be modified by below codes. How much TargetApi had used?

if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
  do something... 
}
else {
  do other things...   // here use older Android API
}

**Comment by 4ntoine** [comment]
The annotation is not a problem but actually required Android 21 WebClient signitature is - we need access to request headers to get `referrer`. Otherwise ad blocking quality will not be good enough. So i can say that actually `AdblockWebView` requires 21 anyway.

**Comment by Humilton** [comment]
Oh , yes, sorry for waste you time. I am not deep into the code.

**Comment by 4ntoine** [comment]
You can use `AdblockWebView` instead of `WebView`, see Demo app https://github.com/adblockplus/libadblockplus-android/tree/master/adblock-android-webviewapp

**Comment by jamescarl15** [comment]
@4ntoine what I meant is, how can I add this to dependency? Like, "compile 'com.support...'" or "implementation 'com.support'.."

**Comment by jamescarl15** [comment]
@4ntoine Can you provide a simple instruction? In the "readme" file, can't understand a bit.. :/ I'd be great if you could! 👍

**Comment by 4ntoine** [comment]
What is not clear in Readme?

**Comment by jamescarl15** [comment]
@4ntoine I don't know where to start... I don't have any idea importing a local library. Should I download the source? Something like that

**Comment by 4ntoine** [comment]
Start from cloning this repository:
git clone https://github.com/adblockplus/libadblockplus-android.git

Then follow instructions from readme.

**Comment by jamescarl15** [comment]
@4ntoine `Build command failed.


Error while executing process C:\Program Files (x86)\Android\android-sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\Users\JC\Desktop\EasyClaimCoinPot\subProject\adblock-android\jni\Android.mk NDK_APPLICATION_MK=C:\Users\JC\Desktop\EasyClaimCoinPot\subProject\adblock-android\jni\Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=0 APP_PLATFORM=android-16 NDK_OUT=C:/Users/JC/Desktop/EasyClaimCoinPot/subProject/adblock-android/build/intermediates/ndkBuild/abi_x86/release/obj NDK_LIBS_OUT=C:\Users\JC\Desktop\EasyClaimCoinPot\subProject\adblock-android\build\intermediates\ndkBuild\abi_x86\release\lib APP_ABI=x86 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}


'C:\Program' is not recognized as an internal or external command,


operable program or batch file.


Build command failed.


Error while executing process C:\Program Files (x86)\Android\android-sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\Users\JC\Desktop\EasyClaimCoinPot\subProject\adblock-android\jni\Android.mk NDK_APPLICATION_MK=C:\Users\JC\Desktop\EasyClaimCoinPot\subProject\adblock-android\jni\Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=0 APP_PLATFORM=android-16 NDK_OUT=C:/Users/JC/Desktop/EasyClaimCoinPot/subProject/adblock-android/build/intermediates/ndkBuild/abi_all/release/obj NDK_LIBS_OUT=C:\Users\JC\Desktop\EasyClaimCoinPot\subProject\adblock-android\build\intermediates\ndkBuild\abi_all\release\lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}


'C:\Program' is not recognized as an internal or external command,


operable program or batch file.


Build command failed.


Error while executing process C:\Program Files (x86)\Android\android-sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\Users\JC\Desktop\EasyClaimCoinPot\subProject\adblock-android\jni\Android.mk NDK_APPLICATION_MK=C:\Users\JC\Desktop\EasyClaimCoinPot\subProject\adblock-android\jni\Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=0 APP_PLATFORM=android-16 NDK_OUT=C:/Users/JC/Desktop/EasyClaimCoinPot/subProject/adblock-android/build/intermediates/ndkBuild/abi_arm/release/obj NDK_LIBS_OUT=C:\Users\JC\Desktop\EasyClaimCoinPot\subProject\adblock-android\build\intermediates\ndkBuild\abi_arm\release\lib APP_ABI=armeabi-v7a APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}


'C:\Program' is not recognized as an internal or external command,


operable program or batch file.


Build command failed.


Error while executing process C:\Program Files (x86)\Android\android-sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\Users\JC\Desktop\EasyClaimCoinPot\subProject\adblock-android\jni\Android.mk NDK_APPLICATION_MK=C:\Users\JC\Desktop\EasyClaimCoinPot\subProject\adblock-android\jni\Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-16 NDK_OUT=C:/Users/JC/Desktop/EasyClaimCoinPot/subProject/adblock-android/build/intermediates/ndkBuild/abi_arm/debug/obj NDK_LIBS_OUT=C:\Users\JC\Desktop\EasyClaimCoinPot\subProject\adblock-android\build\intermediates\ndkBuild\abi_arm\debug\lib APP_ABI=armeabi-v7a APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}


'C:\Program' is not recognized as an internal or external command,


operable program or batch file.


All flavors must now belong to a named flavor dimension. Learn more at https://d.android.com/r/tools/flavorDimensions-missing-error-message.html


Build command failed.


Error while executing process C:\Program Files (x86)\Android\android-sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\Users\JC\Desktop\EasyClaimCoinPot\subProject\adblock-android\jni\Android.mk NDK_APPLICATION_MK=C:\Users\JC\Desktop\EasyClaimCoinPot\subProject\adblock-android\jni\Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-16 NDK_OUT=C:/Users/JC/Desktop/EasyClaimCoinPot/subProject/adblock-android/build/intermediates/ndkBuild/abi_all/debug/obj NDK_LIBS_OUT=C:\Users\JC\Desktop\EasyClaimCoinPot\subProject\adblock-android\build\intermediates\ndkBuild\abi_all\debug\lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}


'C:\Program' is not recognized as an internal or external command,


operable program or batch file.


Build command failed.


Error while executing process C:\Program Files (x86)\Android\android-sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\Users\JC\Desktop\EasyClaimCoinPot\subProject\adblock-android\jni\Android.mk NDK_APPLICATION_MK=C:\Users\JC\Desktop\EasyClaimCoinPot\subProject\adblock-android\jni\Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=1 APP_PLATFORM=android-16 NDK_OUT=C:/Users/JC/Desktop/EasyClaimCoinPot/subProject/adblock-android/build/intermediates/ndkBuild/abi_x86/debug/obj NDK_LIBS_OUT=C:\Users\JC\Desktop\EasyClaimCoinPot\subProject\adblock-android\build\intermediates\ndkBuild\abi_x86\debug\lib APP_ABI=x86 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}


'C:\Program' is not recognized as an internal or external command,


operable program or batch file.


Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :subProject:adblock-android.
Open File
Show Details


Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve project :subProject:adblock-android.
Open File
Show Details


Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve project :subProject:adblock-android.
Open File
Show Details


Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve project :subProject:adblock-android.
Open File
Show Details


Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve project :subProject:adblock-android.
Open File
Show Details
`

I'm getting error importing it

**Comment by 4ntoine** [comment]
You forgot to call `ensure_dependencies.py` so you don't have required deps.
Please follow instuctions in readme carefully.

**Comment by jamescarl15** [comment]
@4ntoine where i should put that?

**Comment by 4ntoine** [comment]
https://github.com/adblockplus/libadblockplus-android/blob/master/ensure_dependencies.py

**Comment by jamescarl15** [comment]
@4ntoine i don't know how to do that.. But, after I imported correctly, this appears 'Could not find method getAbiFlavor() for arguments [] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
Open File
'
is that python file?

**Comment by Jeffin21** [comment]
we changed to adblock webview , and it works fine. where can i edit the host file. i added some changes to host.txt file inside the project not getting any effect in my project , 


09-11 16:28:08.386 10032-10204/W/System.err: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object org.adblockplus.libadblockplus.android.AdblockEngineProvider.getEngineLock()' on a null object reference
09-11 16:28:08.393 10032-10204/ W/System.err:     at org.adblockplus.libadblockplus.android.webview.AdblockWebView$AdblockWebViewClient.shouldInterceptRequest(AdblockWebView.java:836)
        at org.adblockplus.libadblockplus.android.webview.AdblockWebView$AdblockWebViewClient.shouldInterceptRequest(AdblockWebView.java:959)
        at com.android.webview.chromium.WebViewContentsClientAdapter.shouldInterceptRequest(WebViewContentsClientAdapter.java:54)
        at org.chromium.android_webview.AwContents$BackgroundThreadClientImpl.shouldInterceptRequest(AwContents.java:9)
        at org.chromium.android_webview.AwContentsBackgroundThreadClient.shouldInterceptRequestFromNative(AwContentsBackgroundThreadClient.java:11)
09-11 16:28:08.394 10032-10204/hromium: [FATAL:jni_android.cc(232)] Please include Java exception stack in crash report

**Pull request closed without merging**
